pipeline {
    agent any

    tools {
        // Specify the correct names of JDK and Maven installations as configured in Jenkins
        jdk 'JAVA_HOME' // Make sure this matches the configured JDK in Jenkins
        maven 'MAVEN_HOME' // Make sure this matches the configured Maven version in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the repository
                git branch: 'master', url: 'https://github.com/preetam988-sanks/HelloWorld.git'
            }
        }

        stage('Build') {
            steps {
                // Run Maven clean and install
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Run unit tests
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                // Package the Java application into a JAR file
                sh 'mvn package'
            }
        }

        stage('Run') {
            steps {
                // Run the JAR file generated by Maven
                sh 'java -jar target/HelloWorld-1.0-SNAPSHOT.jar' // Replace with the correct JAR file name
            }
        }
    }

    post {
        always {
            // Archive the JAR file for download or future use
            archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: true
        }

        success {
            // Notify if the build is successful
            echo 'Build succeeded!'
        }

        failure {
            // Notify if the build fails
            echo 'Build failed.'
        }
    }
}
