pipeline {
    agent any

    tools {
        // Install JDK and Maven
        jdk 'JDK 11' // Make sure to match the JDK version you have configured in Jenkins
        maven 'Maven 3.9.9' // Match Maven version in Jenkins configuration
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the repository
                git branch: 'main', url: 'https://github.com/preetam988-sanks/HelloWorld.git'
            }
        }

        stage('Build') {
            steps {
                // Run Maven clean and install
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Run unit tests
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                // Package the Java application into a JAR file
                sh 'mvn package'
            }
        }

        stage('Run') {
            steps {
                // Run the JAR file generated by Maven
                sh 'java -jar target/your-app-name-1.0-SNAPSHOT.jar'
            }
        }
    }

    post {
        always {
            // Archive the JAR file for download or future use
            archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: true
        }

        success {
            // Notify if the build is successful
            echo 'Build succeeded!'
        }

        failure {
            // Notify if the build fails
            echo 'Build failed.'
        }
    }
}
